export const servicios = [

    {id: 0, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Toxina botulínica',
        descripcion: 'La toxina botulínica es una neurotoxina la cuál actúa relajando temporalmente los músculos responsables de las arrugas de expresión',
        explicacion: 'La toxina botulínica es uno de los tratamientos de rejuvenecimiento facial más efectivos y solicitados en la medicina estética actual. Se trata de una neurotoxina aplicada de forma médica que actúa relajando temporalmente los músculos responsables de las arrugas de expresión. Su principal objetivo es suavizar las líneas existentes y prevenir que se profundicen con el tiempo, devolviendo al rostro un aspecto notablemente más descansado, fresco y natural, sin perder la expresividad propia de cada paciente.',
        img:'/servicios/facial/TBTS.webp',
        video:"https://www.youtube.com/embed/XXjrG7Wy8sE?si=c-Zp2Ix_xqoH6Q-E"
    },

    {id: 3, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Relleno de hialurónico',
        descripcion: 'El relleno de labios es un tratamiento inyectable que permite dar volumen, mejorar el contorno, corregir asimetrías y aportar hidratación profunda. Se utiliza ácido hialurónico, una sustancia biocompatible y reabsorbible que el cuerpo produce de manera natural.',
        explicacion: ' Los rellenos de ácido hialurónico representan el estándar de oro en la medicina estética para rejuvenecer, perfilar y armonizar las estructuras del rostro de forma inmediata y no quirúrgica. Este procedimiento médico consiste en la aplicación infiltrada de un gel biocompatible y reabsorbible que se integra de manera perfecta a los tejidos del paciente. Su principal función radica en restaurar el volumen perdido debido al envejecimiento cronológico, suavizar surcos profundos y redefinir contornos faciales desdibujados. Al tratarse de una sustancia que se encuentra de forma natural en el propio organismo, garantiza un procedimiento altamente seguro, predecible y diseñado para lograr una apariencia notablemente fresca, descansada y natural.',
        video:"https://www.youtube.com/embed/fkJ9tg4GTVQ?si=57Je01Q-Pgd5XYAW",
        img:'/servicios/facial/RAHP.webp'
    },
    {id: 7, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Sunekos',
        descripcion: 'Es un bioestimulador dérmico inyectable compuesto por ácido hialurónico no reticulado combinado con aminoácidos específicos, que se utiliza para la regeneración de la matriz extra celular, ayudando a estimular la síntesis fisiológica de colágeno tipo I y III y elastina.',
        explicacion: 'Los bioestimuladores de colágeno representan la última revolución en la medicina estética regenerativa para combatir la flacidez y el descolgamiento de los tejidos de forma natural y altamente duradera. Este procedimiento médico consiste en la infiltración de sustancias biocompatibles y reabsorbiblesA diferencia de los rellenos tradicionales, su principal función no es aportar volumen artificial, sino inducir a los fibroblastos a producir grandes cantidades de colágeno y elastina nuevos. Como resultado, se genera una reestructuración interna de la dermis que devuelve la firmeza, define el óvalo facial y promueve un efecto lifting progresivo y un rejuvenecimiento tridimensional genuino.',
        img:'/servicios/facial/S.webp'
    },
    {id: 8, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Bioestimuladores',
        descripcion: 'Los bioestimuladores de colágeno representan la última revolución en la medicina estética regenerativa para combatir la flacidez y el descolgamiento de los tejidos de forma natural y altamente duradera.',
        explicacion: 'Los bioestimuladores de colágeno representan la última revolución en la medicina estética regenerativa para combatir la flacidez y el descolgamiento de los tejidos de forma natural y altamente duradera. Este procedimiento médico consiste en la infiltración de sustancias biocompatibles y reabsorbibles —como la hidroxiapatita de calcio (Radiesse), el ácido poli-L-láctico (Sculptra) o fórmulas híbridas de última generación (HArmonyCa)— destinadas a activar las células de la propia piel. A diferencia de los rellenos tradicionales, su principal función no es aportar volumen artificial, sino inducir a los fibroblastos a producir grandes cantidades de colágeno y elastina nuevos. Como resultado, se genera una reestructuración interna de la dermis que devuelve la firmeza, define el óvalo facial y promueve un efecto lifting progresivo y un rejuvenecimiento tridimensional genuino.',
        img:'/servicios/facial/radiesse.webp',
        video:"https://www.youtube.com/embed/_7AAKW3lEPg?si=dfO6v3Q6mFoLU6NI"
    },
    {id: 11, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Exosomas',
        descripcion: 'Los exosomas son vesículas celulares que actúan como mensajeros biológicos. En estética se utilizan para estimular la regeneración celular profunda.',
        explicacion: 'Los exosomas representan la última revolución en medicina estética y regenerativa gracias a su avanzada capacidad de bioestimulación celular. Estas diminutas vesículas celulares actúan como mensajeros biológicos de alta precisión, transportando lípidos, proteínas y factores de crecimiento directamente hacia las células dañadas para ordenarles que inicien un proceso de autorreparación profunda. Los mismos desencadenan una renovación interna incomparable, convirtiéndose en la terapia innovadora por excelencia para acelerar la curación de los tejidos y rejuvenecer la apariencia global de la piel sin recurrir a técnicas agresivas.',
        img:'/servicios/facial/exosomas.webp',
        video:"https://www.youtube.com/embed/otDZZ2sL_Zk?si=uhf45KnrMbQKArG5"
    },
    {id: 12, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Hilos tensores PDO',
        descripcion: 'Son hilos reabsorbibles utilizados para producir rejuvenecimiento facial mediante efecto tensor y bio estimulación dérmica.',
        explicacion: 'Los hilos de Polidioxanona (PDO) representan uno de los tratamientos médicos más innovadores y demandados para combatir de forma segura los signos de la flacidez y el envejecimiento del rostro. Este procedimiento consiste en la introducción subdérmica de hilos completamente reabsorbibles y biocompatibles que actúan bajo un doble mecanismo: generan un soporte estructural inmediato con efecto tensor y promueven una bioestimulación dérmica profunda a mediano plazo. Si bien es importante destacar que no reemplazan los resultados de una cirugía de estiramiento facial, se consolidan como la alternativa médica no quirúrgica ideal para recuperar los contornos perdidos, mejorar la calidad global de la piel y aportar un tensado natural y progresivo.',
        img:'/servicios/facial/H.webp',
        video:"https://www.youtube.com/embed/8jleo2LSjb4?si=bl4R5d2uUrmE211U"
    },
    {id: 13, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Mesoterapia',
        descripcion: 'La Mesoterapia Facial consiste en la aplicación de pequeñas cantidades de activos específicos (vitaminas, antioxidantes, ácido hialurónico, minerales) directamente en la piel mediante microinyecciones.',
        explicacion: 'La mesoterapia facial es un tratamiento médico-estético de bioestimulación y nutrición celular diseñado para devolverle la vitalidad y frescura natural al rostro desde sus capas más internas. Este procedimiento consiste en la aplicación de microinyecciones superficiales que introducen de forma directa en la piel un exclusivo cóctel de activos específicos de grado médico, tales como ácido hialurónico, vitaminas, antioxidantes y minerales. Su acción localizada convierte a esta terapia en la alternativa ideal para revertir el daño ambiental cotidiano, aportando una hidratación profunda que revitaliza las pieles ',
        img:'/servicios/facial/mesop.webp',
        video:"https://www.youtube.com/embed/0pNRQ3oGm0o?si=f0f2XJv7gRg9sq12"
    },
    {id: 14, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Microneedling: Dermaglow e Hidralips',
        descripcion: 'El microneedling es uno de los tratamientos médicos no invasivos más eficaces y revolucionarios para restaurar por completo la textura, firmeza y juventud de la piel de forma mecánica y natural.',
        explicacion: 'El microneedling es uno de los tratamientos médicos no invasivos más eficaces y revolucionarios para restaurar por completo la textura, firmeza y juventud de la piel de forma mecánica y natural. Este procedimiento consiste en la utilización de un dispositivo médico de última generación provisto de microagujas ultra finas que realizan microperforaciones controladas en la superficie cutánea, desencadenando el proceso natural de autocuración del organismo. Al activar esta respuesta biológica, se estimula de manera profunda la producción de colágeno y elastina nuevos, al mismo tiempo que se crean microcanales que multiplican la absorción de los principios activos aplicados durante la sesión. Su versatilidad lo convierte en el aliado definitivo para renovar la superficie de la piel y corregir imperfecciones sin necesidad de tiempos de recuperación prolongados.',
        img:'/servicios/facial/microneed.jpg'
    },
    {id: 15, 
        rama: "Estética Facial",
        servicio:  'Facial',
        subservicio: 'Peeling',
        descripcion: 'El peeling químico es uno de los tratamientos dermatológicos y estéticos más clásicos, seguros y efectivos para renovar la piel desde las capas más profundas y mejorar múltiples alteraciones cutáneas.',
        explicacion: 'El peeling químico es uno de los tratamientos dermatológicos y estéticos más clásicos, seguros y efectivos para renovar la piel desde las capas más profundas y mejorar múltiples alteraciones cutáneas. Este procedimiento consiste en la aplicación de sustancias y activos médicos seleccionados sobre la superficie cutánea para provocar una exfoliación controlada. El proceso elimina las células muertas y las capas dañadas, acelerando el proceso de renovación celular y estimulando la producción natural de colágeno y elastina. Como resultado, se logra una piel visiblemente más suave, luminosa, firme y uniforme.',
        img:'/servicios/facial/peeling.webp'
    },
    {id: 16, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Plasma Rico en Plaquetas',
        descripcion: 'El PRP (Plasma Rico en Plaquetas) es un tratamiento regenerativo que utiliza la propia sangre del paciente. Se extrae una pequeña muestra, se procesa para concentrar las plaquetas y luego se aplica en la zona a tratar.',
        explicacion: ' El Plasma Rico en Plaquetas (PRP) es un tratamiento médico de bioestimulación cutánea y regenerativa de vanguardia que aprovecha los recursos naturales del propio organismo para rejuvenecer los tejidos desde el interior. Este procedimiento consiste en la extracción de una pequeña muestra de sangre del paciente, la cual se somete a un proceso de centrifugado y separación clínica para concentrar las plaquetas esenciales. Posteriormente, este plasma autólogo y altamente purificado se aplica mediante microinyecciones en la zona a tratar, garantizando un procedimiento biológicamente seguro, libre de alérgenos y adaptado de forma única a las necesidades de la piel.',
        img:'/servicios/facial/PRP.webp',
        video:"https://www.youtube.com/embed/qx9fDqrF9JY?si=k0Ve3WMoJYTa0IPX"
    },
    {id: 17, 
        rama: "Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Mesoterapia Corporal',
        descripcion: 'La mesoterapia corporal es uno de los tratamientos médicos estéticos mínimamente invasivos más eficientes y solicitados.',
        explicacion: 'La mesoterapia corporal es uno de los tratamientos médicos estéticos mínimamente invasivos más eficientes y solicitados para mejorar la salud de los tejidos desde el interior. Consiste en la aplicación de microinyecciones con activos específicos directamente en la capa media de la piel de la zona a tratar, logrando una acción ultra localizada, rápida y efectiva.',
        img:'/servicios/corporal/MC.webp'
    },
    {id: 18, 
        rama: "Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Fosfatidilcolina',
        descripcion: 'La fosfatidilcolina es uno de los tratamientos médicos inyectables más reconocidos y efectivos a nivel mundial para reducir la adiposidad localizada de forma segura y sin recurrir a procedimientos quirúrgicos.',
        explicacion: 'La fosfatidilcolina es uno de los tratamientos médicos inyectables más reconocidos y efectivos a nivel mundial para reducir la adiposidad localizada de forma segura y sin recurrir a procedimientos quirúrgicos. Este principio activo de origen natural se aplica mediante microinyecciones precisas directamente en el tejido adiposo, donde actúa rompiendo y disolviendo las membranas de las células grasas para facilitar su posterior eliminación natural a través del organismo. Su uso clínico está diseñado exclusivamente para modelar y reducir centímetros en zonas rebeldes que no responden a la dieta ni al ejercicio físico, consolidándose como una herramienta clave para esculpir la silueta de manera progresiva.',
        img:'/servicios/corporal/F.webp'
    },
    {id: 19,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Enzimas',
        descripcion: 'Las enzimas lipolíticas son sustancias que se aplican mediante microinyecciones en zonas con grasa localizada como abdomen, flancos, papada o pantalón de montar.',
        explicacion: 'Las enzimas lipolíticas representan uno de los tratamientos médicos más avanzados y eficaces para la reducción de adiposidad localizada sin necesidad de pasar por un quirófano. Este procedimiento consiste en la aplicación de microinyecciones con principios activos biológicos altamente específicos directamente en las zonas críticas a tratar, tales como el abdomen, los flancos, la papada o el pantalón de montar. Su acción se centra en favorecer la ruptura de las células grasas para que el organismo las elimine de forma natural, convirtiéndose en la alternativa ideal para modelar zonas rebeldes que no responden adecuadamente a la dieta o al ejercicio físico.',
        img:'/servicios/corporal/EL.webp',
        video:"https://www.youtube.com/embed/MPsw-Ip8hBs?si=XEK7PSS-0wYjVyhW"
    },
    {id: 20,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Alidya',
        descripcion: 'Alidya es un tratamiento médico específico para la celulitis. Actúa sobre una de sus causas principales: la acumulación de toxinas y alteración del tejido subcutáneo.',
        explicacion: 'Alidya® es el primer tratamiento médico inyectable a nivel mundial diseñado específicamente para combatir la celulitis (PEFE) desde su origen. A diferencia de otros procedimientos superficiales, Alidya® actúa directamente sobre una de las causas principales de esta afección: la acumulación de toxinas extracelulares, la alteración del tejido subcutáneo y el daño en la microcirculación local. Su fórmula patentada ejerce una acción profunda que ayuda a neutralizar y eliminar los elementos nocivos (como el exceso de hierro y metales pesados) que inflaman el tejido adiposo, restaurando la salud interna de la piel.',
        img:'/servicios/corporal/A.webp',
        video:"https://www.youtube.com/embed/QqvBCwzVYcw?si=ia1miUhS2HgHFc0T"
    },
    {id: 21,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Carboxiterapia',
        descripcion: 'La carboxiterapia consiste en la aplicación de dióxido de carbono medicinal debajo de la piel mediante una aguja muy fina. Este gas mejora la oxigenación de los tejidos y estimula la circulación sanguínea',
        explicacion: 'La carboxiterapia es un tratamiento estético y médico de vanguardia, mínimamente invasivo y altamente eficaz para rejuvenecer los tejidos desde el interior. Consiste en la aplicación controlada de dióxido de carbono (CO2) de grado medicinal justo debajo de la piel, utilizando una aguja ultra fina. Este gas, al ser introducido en el organismo, provoca una respuesta natural e inmediata: una potente vasodilatación que mejora drásticamente la oxigenación celular y estimula de forma profunda la circulación sanguínea local. ',
        img:'/servicios/corporal/C.webp'
    },
    {id: 22,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Hilos PDO',
        descripcion: 'Es un procedimiento mínimamente invasivo donde se colocan hilos de polidioxanona (PDO)',
        explicacion: 'Los hilos corporales de Polidioxanona (PDO) representan uno de los tratamientos médicos no quirúrgicos más eficientes y avanzados para combatir la flacidez y la pérdida de firmeza en el cuerpo. Este procedimiento mínimamente invasivo consiste en la colocación estratégica de hilos reabsorbibles y biocompatibles justo debajo de la superficie cutánea, actuando como una red de soporte interna que genera un efecto tensor inmediato. Su principal beneficio radica en la estimulación profunda de la neocolagenogénesis (producción de colágeno nuevo) a mediano plazo, logrando restaurar la elasticidad, turgencia y calidad global de la piel de forma completamente natural y progresiva.',
        img:'/servicios/corporal/H.webp',
        video:"https://www.youtube.com/embed/4izjvK4n76A?si=Kl7_2xZEQKqmVfxI"
    },
    {id: 23,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Plasma Rico en Plaquetas',
        descripcion: 'El Plasma Rico en Plaquetas (PRP) corporal con enfoque de recuperación es un tratamiento médico regenerativo de alta precisión diseñado para acelerar la reparación natural de los tejidos.',
        explicacion: 'El Plasma Rico en Plaquetas (PRP) corporal con enfoque de recuperación es un tratamiento médico regenerativo de alta precisión diseñado para acelerar la reparación natural de los tejidos, articulaciones y zonas propensas al desgaste o sobreexigencia física. Este procedimiento biológico consiste en la extracción de una pequeña muestra de sangre del propio paciente, la cual se procesa mediante un sistema de centrifugado clínico para aislar y concentrar los factores de crecimiento presentes en las plaquetas. Posteriormente, este plasma autólogo purificado se aplica mediante microinyecciones localizadas directamente en las áreas afectadas, como hombros, rodillas, codos o tendones, estimulando una profunda autoreparación celular. Al utilizar los recursos biológicos del propio organismo, garantiza un proceso de curación interno 100% natural, seguro y libre de reacciones alérgicas o rechazo.',
        img:'/servicios/corporal/PRPC.webp'
    },
    {id: 24, 
        rama: "Tratamientos Capilares",
        servicio: 'Capilar',
        subservicio: 'Mesoterapia Capilar',
        descripcion: 'Tratamiento que consiste en aplicar activos específicos directamente en el cuero cabelludo para fortalecer el folículo piloso.',
        explicacion: 'La mesoterapia capilar es un tratamiento médico-estético altamente efectivo y de acción localizada diseñado para combatir la caída del cabello y restaurar la salud del cuero cabelludo desde la raíz. Este procedimiento consiste en la aplicación de microinyecciones superficiales que introducen directamente en la zona folicular un exclusivo cóctel de activos específicos, que incluye vitaminas, aminoácidos, minerales y factores de coenzimas. Su principal objetivo es nutrir profundamente y fortalecer el folículo piloso, convirtiéndose en la alternativa médica ideal para frenar los procesos iniciales de afinamiento capilar, mejorar la densidad y revitalizar el cabello debilitado sin necesidad de cirugías.',
        img:'/servicios/capilar/MC.webp',
        video:"https://www.youtube.com/embed/ZiXd9wKManA?si=5PaZg75taRlB6eJg"
    },
    {id: 25, 
        rama: "Tratamientos Capilares",
        servicio: 'Capilar',
        subservicio: 'Plasma Rico en Plaquetas',
        descripcion: 'El Plasma Rico en Plaquetas (PRP) capilar es uno de los tratamientos médicos regenerativos más avanzados y eficaces para frenar la caída del vello y estimular la recuperación del cabello debilitado.',
        explicacion: 'El Plasma Rico en Plaquetas (PRP) capilar es uno de los tratamientos médicos regenerativos más avanzados y eficaces para frenar la caída del vello y estimular la recuperación del cabello debilitado. Este procedimiento biológico consiste en la extracción de una pequeña muestra de sangre del propio paciente, la cual se procesa mediante un sistema de centrifugado clínico para aislar y concentrar los factores de crecimiento presentes en las plaquetas. Posteriormente, este plasma autólogo purificado se aplica mediante microinyecciones directamente en el cuero cabelludo, llegando de forma exacta a la raíz folicular para reactivar el metabolismo celular. Al ser un tratamiento que utiliza los recursos del propio organismo, es un procedimiento 100% natural, bioseguro y libre de efectos secundarios o reacciones alérgicas.',
        img:'/servicios/capilar/PRPC.webp'
    },
    {id: 26, 
        rama: "Tratamientos con Láser",
        servicio: 'Laser',
        subservicio: 'Depilación definitiva',
        descripcion: 'La depilación láser Soprano Ice® es el sistema de eliminación de vello definitivo más seguro, eficaz y demandado a nivel mundial.',
        explicacion: 'La depilación láser Soprano Ice® es el sistema de eliminación de vello definitivo más seguro, eficaz y demandado a nivel mundial. Este tratamiento utiliza una avanzada tecnología lumínica que emite ráfagas de energía directamente hacia el folículo piloso, logrando debilitar la raíz del pelo de forma progresiva sin dañar los tejidos circundantes. Debido a que el láser actúa exclusivamente sobre los vellos que se encuentran en su fase activa de crecimiento (fase anágena), el protocolo requiere de varias sesiones consecutivas para garantizar que, con el paso del tiempo, el vello se debilite por completo hasta desaparecer de manera permanente en la gran mayoría de los casos.',
        img:'/servicios/laser/DD.webp',
        video:"https://www.youtube.com/embed/-E6Iybi78xQ?si=WbhRwOEcQB9Z19h-"
    },
    {id: 27, 
        rama: "Tratamientos con Láser",
        servicio: 'Laser',
        subservicio: 'HIFU 12 D',
        descripcion: 'El sistema HIFU (Ultrasonido Focalizado de Alta Intensidad, por sus siglas en inglés) es una de las tecnologías médicas no invasivas más potentes y avanzadas para combatir la flacidez',
        explicacion: 'El sistema HIFU (Ultrasonido Focalizado de Alta Intensidad, por sus siglas en inglés) es una de las tecnologías médicas no invasivas más potentes y avanzadas para combatir la flacidez y lograr un rejuvenecimiento estructural profundo. Este procedimiento consiste en la aplicación de ondas de ultrasonido que convergen con máxima precisión en las capas más internas de la dermis y el tejido subcutáneo sin generar ningún tipo de lesión o daño en la superficie de la piel. Su acción térmica concentrada desencadena un proceso biológico de reparación que estimula la producción natural de nuevo colágeno y elastina, generando un efecto tensor progresivo que devuelve notablemente la firmeza y la definición a las estructuras tanto faciales como corporales.',
        img:'/servicios/laser/H.webp',
        video:"https://www.youtube.com/embed/tFRJ2Vvx5_I?si=851KjJuZmIztJbpQ"
    },
    {id: 28, 
        rama: "Tratamientos con Láser",
        servicio: 'Laser',
        subservicio: 'Nordlys',
        descripcion: 'El sistema Nordlys® (de Candela) es la multiplataforma médica y estética más avanzada del mundo en tecnología de Luz Pulsada Intensa (IPL - SWT®) y láser fraccionado.',
        explicacion: 'El sistema Nordlys® (de Candela) es la multiplataforma médica y estética más avanzada del mundo en tecnología de Luz Pulsada Intensa (IPL - SWT®) y láser fraccionado. Este revolucionario equipo médico permite combinar múltiples tratamientos en una sola sesión, ofreciendo una solución integral, segura y altamente eficaz para transformar la salud y apariencia de la piel. Permite mejorar manchas, rojeces, poros dilatados, cicatrices de acné y signos de envejecimiento, estimulando además la producción natural de colágeno. Gracias a sus diferentes tecnologías, los tratamientos pueden adaptarse a las necesidades de cada paciente, logrando resultados naturales y progresivos. Este es un tratamiento rápido, mínimamente invasivo y con poco tiempo de recuperación, lo que la convierte en una excelente opción para quienes desean mejorar la calidad de la piel y rejuvenecer su apariencia sin procedimientos quirúrgicos.',
        img:'/servicios/laser/N.webp'
    }, 
        {id: 29,
        rama:"Medicina Funcional",
        servicio: 'Funcional',
        subservicio: 'Consulta',
        descripcion: 'La consulta de medicina funcional, nutricional y hormonal es un espacio médico de alta complejidad diseñado para descubrir y tratar la causa raíz de los desequilibrios que afectan tu salud.',
        explicacion: 'La consulta de medicina funcional, nutricional y hormonal es un espacio médico de alta complejidad diseñado para descubrir y tratar la causa raíz de los desequilibrios que afectan tu salud, yendo más allá de la simple supresión de los síntomas. Bajo un enfoque clínico profundamente personalizado y basado en la salud integral, este tratamiento evalúa de forma conjunta tu perfil metabólico, tus niveles hormonales y tus hábitos diarios mediante estudios clínicos de laboratorio. El objetivo principal es trazar una estrategia médica a tu medida que restaure el equilibrio endocrino, optimice tu nutrición celular y promueva una longevidad saludable y activa, devolviéndole al organismo su vitalidad y funcionamiento óptimo natural.',
        img:'/servicios/funcional/DP.webp'
    },
        {id: 30, 
        rama: "Medicina Funcional",
        servicio: 'Funcional',
        subservicio: 'Pellet de testosterona',
        descripcion: 'El pellet de testosterona es un tratamiento médico avanzado de reposición hormonal bioidéntica diseñado para devolver el equilibrio y la vitalidad al organismo.',
        explicacion: 'El pellet de testosterona es un tratamiento médico avanzado de reposición hormonal bioidéntica diseñado para devolver el equilibrio y la vitalidad al organismo. Consiste en la colocación de un pequeño implante subcutáneo que libera esta hormona de forma constante y gradual durante varios meses, imitando el funcionamiento natural del cuerpo. Este procedimiento se indica de manera exclusiva a personas con un déficit hormonal diagnosticado mediante estudios clínicos previos, garantizando un abordaje seguro, preciso y 100% personalizado según las necesidades metabólicas de cada paciente.',
        img:'/servicios/funcional/PT.webp',
        video:"https://www.youtube.com/embed/ZskbM2X_jVw?si=MpMdb7qWfC7g7p6S"
    },
        {id: 31, 
        rama: "Medicina Funcional",
        servicio: 'Funcional',
        subservicio: 'Sueroterapia',
        descripcion: 'La sueroterapia consiste en la administración intravenosa de vitaminas, minerales y antioxidantes personalizados según las necesidades del paciente.',
        explicacion: 'La sueroterapia es un tratamiento médico de vanguardia centrado en la optimización de la salud y el bienestar integral desde el nivel celular. Consiste en la administración por vía intravenosa de un cóctel personalizado de vitaminas, minerales, aminoácidos y antioxidantes, seleccionados de forma exacta según los requerimientos biológicos de cada persona. Al ingresar directamente al torrente sanguíneo, el tratamiento evita el proceso de digestión, garantizando una absorción del 100% de los nutrientes de manera inmediata y efectiva. ',
        img:'/servicios/funcional/ST.webp'
    },
]