export const servicios = [

    {id: 0, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Toxina botulínica: Tercio Superior',
        descripcion: 'Son suturas reabsorbibles utilizadas en medicina estética para un efecto lifting no quirúrgico',
        explicacion: 'Los hilos PDO (polidioxanona) son filamentos biocompatibles y reabsorbibles que se colocan debajo de la piel para Tensar, Reafirmar, Estimular colágeno, Mejorar la flacidez. La polidioxanona es un material que se usa hace muchos años en cirugía (como sutura), por lo que es seguro y se reabsorbe naturalmente.',
        img:''
    },
    {id: 1, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Toxina botulínica: Sonrisa Gingival',
        descripcion: 'El PRP es un tratamiento de bioestimulación que utiliza la propia sangre del paciente para rejuvenecer y regenerar la piel de forma natural',
        explicacion: 'Se extrae una pequeña cantidad de sangre. Se centrifuga para separar el plasma rico en plaquetas. Ese plasma concentrado se aplica mediante microinyecciones en el rostro. Las plaquetas contienen factores de crecimiento que estimulan: Producción de colágeno, Formación de elastina, Regeneración celular, Mejoría de la calidad y textura de la piel',
        img:''
    },
    {id: 2, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Toxina botulínica: Bruxismo',
        descripcion: 'El HIFU 12D es un tratamiento de lifting no quirúrgico que utiliza ultrasonido focalizado de alta intensidad para tensar la piel y estimular colágeno en profundidad.',
        explicacion: 'El equipo emite energía ultrasónica que: Penetra en capas profundas de la piel. Llega hasta el sistema SMAS (la misma capa que se trabaja en un lifting quirúrgico), Genera micro puntos de coagulación térmica, Estimula producción intensa de colágeno, La piel se contrae y se reafirma progresivamente.',
        img:''
    },
    {id: 3, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Rellenos de ácido hialurónico: Labios',
        descripcion: 'Los exosomas son nano-vesículas extracelulares que actúan como “mensajeros biológicos”, transportando factores de crecimiento, proteínas y señales regenerativas entre las células.',
        explicacion: 'Los exosomas: Activan fibroblastos, Estimulan producción de colágeno y elastina, Mejoran reparación celular, Disminuyen inflamación, Aumentan la regeneración cutánea, Actúan a nivel celular, no solo superficial.',
        img:''
    },
    {id: 4, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Rellenos de ácido hialurónico: Pómulos',
        descripcion: 'La mesoterapia facial consiste en la aplicación de microinyecciones intradérmicas con activos específicos para rejuvenecer, hidratar y mejorar la calidad de la piel.',
        explicacion: 'PDRN (Polidesoxirribonucleótidos)Estimula regeneración celular profunda, Aumenta producción de colágeno, Mejora cicatrización, Reduce inflamación, Mejora textura y luminosidad. NCTF (New Cellular Treatment Factor): Hidrata profundamente, Revitaliza piel apagada, Mejora tono y luminosidad, Atenúa líneas finas, Previene envejecimiento ',
        img:''
    },
    {id: 5, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Rellenos de ácido hialurónico: Mentón',
        descripcion: 'Es un bioestimulador dérmico a base de hidroxiapatita de calcio (CaHA) que no solo aporta volumen inmediato, sino que estimula la producción natural de colágeno.',
        explicacion: '1️⃣ Efecto inmediato: Aporta volumen y mejora la estructura de la zona tratada. 2️⃣ Efecto biológico progresivo: Estimula los fibroblastos para producir colágeno nuevo, logrando firmeza sostenida en el tiempo. Con el paso de los meses, el gel se reabsorbe y queda el colágeno generado por el propio cuerpo',
        img:''
    },
    {id: 6, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Rellenos de ácido hialurónico: Ojeras',
        descripcion: 'El relleno de labios es un tratamiento estético mínimamente invasivo que utiliza ácido hialurónico para mejorar volumen, definición e hidratación de los labios, respetando la armonía facial.',
        explicacion: 'Es una sustancia naturalmente presente en el cuerpo que: Aporta hidratación, Retiene agua, Da volumen, Mejora elasticidad, Al aplicarse en labios, permite un resultado natural y moldeable.',
        img:''
    },
    {id: 7, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Sunekos',
        descripcion: 'El relleno de labios es un tratamiento estético mínimamente invasivo que utiliza ácido hialurónico para mejorar volumen, definición e hidratación de los labios, respetando la armonía facial.',
        explicacion: 'Es una sustancia naturalmente presente en el cuerpo que: Aporta hidratación, Retiene agua, Da volumen, Mejora elasticidad, Al aplicarse en labios, permite un resultado natural y moldeable.',
        img:''
    },
    {id: 8, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Radiesse',
        descripcion: 'Los rellenos faciales con ácido hialurónico son tratamientos mínimamente invasivos diseñados para restaurar volumen, suavizar arrugas y mejorar la armonía del rostro.',
        explicacion: 'Es una sustancia naturalmente presente en el cuerpo que: Aporta hidratación, Retiene agua, Da volumen, Mejora elasticidad. ZOnas a tratar: Surcos nasogenianos, Líneas de marioneta, Pómulos, Mentón, Mandíbula, Ojeras, Nariz (rinomodelación)',
        img:''
    },
    {id: 9, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Sculptra ',
        descripcion: 'La toxina botulínica es uno de los tratamientos más realizados en medicina estética para suavizar arrugas dinámicas y prevenir el envejecimiento en el tercio superior del rostro.',
        explicacion: 'Qué zonas incluye el tercio superior? Entrecejo (líneas del ceño), Frente, Patas de gallo, Elevación sutil de cejas La toxina: Bloquea temporalmente la contracción muscular, Disminuye la formación de arrugas dinámicas, Previene que las líneas se profundicen, El resultado es una expresión más relajada, sin perder naturalidad.',
        img:''
    },
    {id: 10, 
        rama: "Estética Facial",
        servicio:  'Facial',
        subservicio: 'HarmonyCa',
        descripcion: 'La aplicación de toxina botulínica es un tratamiento mínimamente invasivo que permite corregir la sonrisa gingival, reduciendo la exposición excesiva de encía al sonreír.',
        explicacion: 'Se aplican pequeñas dosis de toxina en los músculos elevadores del labio superior. Esto permite:Disminuir la elevación exagerada del labio, Reducir la cantidad de encía visible, Mantener una expresión natural, El objetivo no es cambiar la sonrisa, sino armonizarla.',
        img:''
    },
    {id: 11, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Exosomas',
        descripcion: 'La aplicación de toxina botulínica puede utilizarse para relajar los músculos que traccionan hacia abajo las comisuras, mejorando la expresión facial.',
        explicacion: 'La toxina se aplica en el músculo depresor del ángulo de la boca. Esto permite: Elevar sutilmente las comisuras, Mejorar el gesto de tristeza, Suavizar la expresión descendente. No rellena el surco, sino que mejora la dinámica muscular.',
        img:''
    },
    {id: 12, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Hilos tensores PDO',
        descripcion: 'La toxina botulínica Full Face es un enfoque avanzado que trata múltiples zonas del rostro en una misma sesión, buscando armonizar la expresión de manera global y natural.',
        explicacion: 'Dependiendo de la evaluación médica: Frente, Entrecejo, Patas de gallo, Elevación de cejas, Sonrisa gingival, Líneas peribucales, Comisuras descendidas, Mentón, Bandas del cuello ¿Cómo funciona? La toxina: Relaja selectivamente músculos hiperactivos, Suaviza arrugas dinámicas, Previene profundización de líneas, Reequilibra la expresión facial. El resultado es un rostro más descansado y armónico, sin perder naturalidad.',
        img:''
    },
    {id: 13, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Profhilo',
        descripcion: 'Las enzimas inyectables se utilizan para mejorar irregularidades y reducir acúmulos localizados. Se suelen utilizar para reducir la "papada" y tratar ojeras',
        explicacion: 'Lipasas (lipolíticas) Actúan sobre células grasas. Se utilizan para:, Reducir adiposidad localizada, Papada, Bolsas grasas leves. Colagenasas: Degradan exceso de colágeno o fibrosis. Indicadas en: Cicatrices por acne, Cicatrices endurecidas. Hialuronidasa: Es una enzima que degrada ácido hialurónico. Se utiliza para: Corregir rellenos mal posicionados, Disolver exceso de producto Ajustar resultados no deseados. Es una herramienta clave en armonización facial responsable.',
        img:''
    },
    {id: 14, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Mesoterapia PDRN y NCTF',
        descripcion: 'Sculptra es un bioestimulador inyectable a base de ácido poli-L-láctico (PLLA) que estimula la producción natural de colágeno, mejorando firmeza, estructura y calidad de la piel de manera progresiva.',
        explicacion: 'Después de su aplicación: Activa los fibroblastos, Estimula producción profunda de colágeno, Mejora densidad y firmeza cutánea, Restaura soporte estructural del rostro. El volumen que se observa no es “producto”, sino colágeno propio generado por el cuerpo. Se indica para contrarrestar: Flacidez facial leve a moderada, Pérdida de volumen estructural, Envejecimiento global del rostro, Cuello y escote',
        img:''
    },
    {id: 15, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Microneedling: Dermaglow e Hidralips',
        descripcion: 'La depilación definitiva con tecnología láser es un tratamiento seguro y eficaz que reduce de manera progresiva y duradera el crecimiento del vello.',
        explicacion: 'El láser emite una luz que: Es absorbida por la melanina del vello, Se transforma en calor, Destruye selectivamente el folículo, Reduce el crecimiento futuro. Solo el vello en fase de crecimiento responde al tratamiento, por eso se realizan varias sesiones. Zonas más frecuentes, Rostro, Axilas, Piernas, Cavado, Espalda, Abdomem, Brazos',
        img:''
    },
    {id: 16, 
        rama: "Estética Facial",
        servicio:  'Facial',
        subservicio: 'Peeling',
        descripcion: 'Los hilos PDO corporales son filamentos reabsorbibles de polidioxanona que se colocan en planos profundos de la piel para mejorar la flacidez y estimular la producción de colágeno en distintas zonas del cuerpo',
        explicacion: 'Tienen un doble efecto: 1️⃣ Efecto tensor inmediato: Generan una leve tracción mecánica que mejora la firmeza. 2️⃣ Bioestimulación progresiva: Estimulan producción de colágeno y elastina, mejorando la calidad de la piel con el tiempo. Aunque el hilo se reabsorbe en meses, el colágeno generado prolonga el resultado.',
        img:''
    },
    {id: 17, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Higiene',
        descripcion: 'Alidya es un tratamiento inyectable diseñado específicamente para mejorar la celulitis y la calidad de la piel corporal.',
        explicacion: 'La celulitis se asocia a: Retención de líquidos, Alteraciones en la microcirculación, Inflamación local, Fibrosis. Alidya ayuda a: Neutralizar toxinas, Mejorar el drenaje, Reducir la inflamación, Optimizar la oxigenación del tejido, El resultado es una piel más uniforme y firme.',
        img:''
    },
    {id: 18, 
        rama: "Estética Facial",
        servicio: 'Facial',
        subservicio: 'Plasma Rico en Plaquetas',
        descripcion: 'La carboxiterapia corporal es un tratamiento médico que consiste en la aplicación subcutánea de dióxido de carbono (CO₂) para mejorar celulitis, flacidez y adiposidad localizada.',
        explicacion: 'Al infiltrarse el CO₂ en la zona tratada: Mejora la microcirculación, Aumenta la oxigenación celular, Estimula producción de colágeno, Favorece el drenaje, Activa el metabolismo de la grasa localizada, El tejido responde volviéndose más firme y uniforme. Indicaciones principales, Celulitis, Flacidez leve a moderada, Estrías, Adiposidad localizada pequeña, Fibrosis post procedimientos',
        img:''
    },
    {id: 19,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Enzimas',
        descripcion: 'El HIFU 12D (High Intensity Focused Ultrasound) es un tratamiento no invasivo que utiliza ultrasonido focalizado de alta intensidad para tensar la piel y estimular la producción profunda de colágeno.',
        explicacion: 'La energía ultrasónica: Penetra en distintas capas de la piel, Llega hasta el sistema SMAS (la misma capa que se trabaja en cirugía), Genera puntos de calor controlados, Estimula producción intensa de colágeno, La piel se reafirma progresivamente. Se utiliza en: Abdomen, Brazos, Muslos, Flancos, Glúteos',
        img:''
    },
    {id: 20,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Alidya',
        descripcion: 'Los exosomas son nano-vesículas biológicas que actúan como mensajeros celulares, estimulando procesos de regeneración profunda y mejorando la calidad del tejido cutáneo.',
        explicacion: 'Los exosomas: Activan fibroblastos, Estimulan producción de colágeno y elastina, Mejoran reparación tisular, Disminuyen inflamación, Optimizar regeneración celular, Actúan a nivel celular, no solo superficial ¿Para qué están indicados?, Flacidez corporal leve, Estrías, Cicatrices, Piel dañada o desvitalizada, Recuperación post HIFU o radiofrecuencia',
        img:''
    },
    {id: 21,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Carboxiterapia',
        descripcion: 'La mesoterapia corporal consiste en la aplicación de microinyecciones intradérmicas con activos específicos para tratar grasa localizada, celulitis, flacidez y mejorar la calidad de la piel.',
        explicacion: 'Mediante pequeñas infiltraciones se administran sustancias que pueden: Estimular el metabolismo local, Favorecer la lipólisis (reducción de grasa), Mejorar la microcirculación, Reducir fibrosis, Estimular colágeno. La formulación se adapta según el objetivo terapéutico ¿Para qué está indicada?, Adiposidad localizada pequeña, Celulitis, Flacidez leve, Estrías, Fibrosis post procedimientos',
        img:''
    },
    {id: 22,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Hilos tensores PDO',
        descripcion: 'Radiesse corporal es un tratamiento bioestimulador a base de hidroxiapatita de calcio (CaHA) que mejora la firmeza y calidad de la piel en distintas zonas del cuerpo.',
        explicacion: 'Radiesse corporal tiene un doble mecanismo: 1️⃣ Estímulo inmediato: Mejora leve de la estructura del tejido. 2️⃣ Bioestimulación profunda: Activa los fibroblastos para producir nuevo colágeno, aumentando firmeza y densidad cutánea. Con el tiempo, el producto se reabsorbe y queda el colágeno generado por el cuerpo ¿Para qué está indicado?, Flacidez corporal leve a moderada, Brazos (flacidez tipo “alas”), Abdomen, Muslos, Rodillas, Glúteos, Rejuvenecimiento de manos',
        img:''
    },
    {id: 23,
        rama:"Estética Corporal",
        servicio: 'Corporal',
        subservicio: 'Plasma Rico en Plaquetas',
        descripcion: 'La toxina botulínica en axilas es un tratamiento indicado para tratar la hiperhidrosis (sudoración excesiva). Reduce significativamente la producción de sudor, mejorando confort y calidad de vida.',
        explicacion: 'La toxina actúa bloqueando temporalmente la señal nerviosa que estimula las glándulas sudoríparas. Esto permite: Disminuir la sudoración excesiva, Reducir humedad constante, Mejorar seguridad y bienestar, No afecta otras funciones del cuerpo ¿Para quién está indicado? Personas con hiperhidrosis axilar, Pacientes que transpiran excesivamente incluso en reposo, Casos donde los antitranspirantes no son suficientes',
        img:''
    },
    {id: 24, 
        rama: "Tratamientos Capilares",
        servicio: 'Capilar',
        subservicio: 'Mesoterapia',
        descripcion: 'La toxina botulínica para bruxismo es un tratamiento mínimamente invasivo que ayuda a relajar los músculos responsables del apretamiento y rechinamiento involuntario de los dientes.',
        explicacion: 'Reduce la tensión mandibular, el dolor y el desgaste dental sin afectar la función normal de la masticación ¿Qué es el bruxismo? El bruxismo es el hábito involuntario de: Apretar los dientes, Rechinar los dientes, Contraer excesivamente los músculos mandibulares, Puede provocar:, Dolor en mandíbula, Cefaleas frecuentes, Contractura cervical, Desgaste dental, Hipertrofia del músculo masetero (mandíbula más ancha). Se aplica toxina en el músculo masetero (y en algunos casos temporal) para: Disminuir la fuerza de contracción muscular, Reducir la tensión excesiva, Aliviar dolor y presión mandibular, Prevenir el desgaste dental. No paraliza completamente el músculo, solo reduce su hiperactividad.',
        img:''
    },
    {id: 25, 
        rama: "Tratamientos Capilares",
        servicio: 'Capilar',
        subservicio: 'Plasma Rico en Plaquetas',
        descripcion: 'El Plasma Rico en Plaquetas (PRP) capilar es un tratamiento de bioestimulación que utiliza los propios factores de crecimiento del paciente para fortalecer el cabello y estimular su crecimiento.',
        explicacion: '¿Cómo funciona? Se extrae una pequeña muestra de sangre, se centrifuga para concentrar el plasma rico en plaquetas, el plasma se aplica mediante microinyecciones en el cuero cabelludo. Las plaquetas liberan factores de crecimiento que: Estimulan el folículo pilos,prolongan la fase de crecimiento del cabello, mejoran la vascularización, fortalecen el cabello debilitado ¿Para qué está indicado? Caída del cabello (efluvio), Alopecia androgenética (en etapas iniciales y moderadas), Cabello fino o debilitado, Post trasplante capilar (para mejorar resultados). Resultados: Disminución de la caída en las primeras semanas, Mejora en grosor y calidad del cabello, Mayor densidad progresiva. Se recomienda un protocolo inicial de 3 a 4 sesiones',
        img:''
    },
    {id: 26, 
        rama: "Tratamientos con Láser",
        servicio: 'Laser',
        subservicio: 'Depilación ',
        descripcion: 'El pellet de testosterona es un tratamiento de terapia hormonal que consiste en la colocación subcutánea de pequeños implantes biodegradables que liberan testosterona de manera sostenida y controlada en el organismo.',
        explicacion: '¿Cómo funciona? El pellet: Se coloca bajo la piel (generalmente en la región glútea). Libera testosterona de forma continua y estable. Mantiene niveles hormonales más constantes que otras formas de administración. La liberación suele mantenerse durante varios meses ¿Para quién está indicado? Puede indicarse en: Hombres con: Hipogonadismo, Fatiga persistente, Disminución de libido, Pérdida de masa muscular, Bajo rendimiento físico. Mujeres (en dosis adecuadas) con:, Déficit androgénico, Disminución del deseo sexual, Fatiga crónica, Cambios asociados a la menopausia. Siempre requiere evaluación médica individual.',
        img:''
    },
    {id: 27, 
        rama: "Tratamientos con Láser",
        servicio: 'Laser',
        subservicio: 'HIFU 12 D',
        descripcion: 'La sueroterapia es un tratamiento que consiste en la administración intravenosa de sueros formulados con vitaminas, minerales, antioxidantes y otros nutrientes, con el objetivo de mejorar el bienestar general y optimizar el funcionamiento del organismo.',
        explicacion: '¿Cómo funciona? A través de una vía intravenosa se administran combinaciones personalizadas que pueden incluir: Vitamina C, Complejo B, Magnesio, Zinc, Aminoácidos, Antioxidantes ¿Para qué está indicada? Fatiga o agotamiento físico, Estrés, Bajos niveles de energía, Déficit vitamínico, Refuerzo del sistema inmunológico, Recuperación post enfermedad o entrenamiento intenso. Permite una absorción directa y rápida, ya que los nutrientes ingresan al torrente sanguíneo sin pasar por el sistema digestivo. La formulación se adapta según las necesidades del paciente.',
        img:''
    },
    {id: 28, 
        rama: "Tratamientos con Láser",
        servicio: 'Laser',
        subservicio: 'Nordlys',
        descripcion: 'La sueroterapia es un tratamiento que consiste en la administración intravenosa de sueros formulados con vitaminas, minerales, antioxidantes y otros nutrientes, con el objetivo de mejorar el bienestar general y optimizar el funcionamiento del organismo.',
        explicacion: '¿Cómo funciona? A través de una vía intravenosa se administran combinaciones personalizadas que pueden incluir: Vitamina C, Complejo B, Magnesio, Zinc, Aminoácidos, Antioxidantes ¿Para qué está indicada? Fatiga o agotamiento físico, Estrés, Bajos niveles de energía, Déficit vitamínico, Refuerzo del sistema inmunológico, Recuperación post enfermedad o entrenamiento intenso. Permite una absorción directa y rápida, ya que los nutrientes ingresan al torrente sanguíneo sin pasar por el sistema digestivo. La formulación se adapta según las necesidades del paciente.',
        img:''
    }, 
        {id: 29,
        rama:"Medicina Funcional",
        servicio: 'Funcional',
        subservicio: 'Descenso de peso',
        descripcion: 'La sueroterapia es un tratamiento que consiste en la administración intravenosa de sueros formulados con vitaminas, minerales, antioxidantes y otros nutrientes, con el objetivo de mejorar el bienestar general y optimizar el funcionamiento del organismo.',
        explicacion: '¿Cómo funciona? A través de una vía intravenosa se administran combinaciones personalizadas que pueden incluir: Vitamina C, Complejo B, Magnesio, Zinc, Aminoácidos, Antioxidantes ¿Para qué está indicada? Fatiga o agotamiento físico, Estrés, Bajos niveles de energía, Déficit vitamínico, Refuerzo del sistema inmunológico, Recuperación post enfermedad o entrenamiento intenso. Permite una absorción directa y rápida, ya que los nutrientes ingresan al torrente sanguíneo sin pasar por el sistema digestivo. La formulación se adapta según las necesidades del paciente.',
        img:''
    },
        {id: 30, 
        rama: "Medicina Funcional",
        servicio: 'Funcional',
        subservicio: 'Pellet de testosterona',
        descripcion: 'La sueroterapia es un tratamiento que consiste en la administración intravenosa de sueros formulados con vitaminas, minerales, antioxidantes y otros nutrientes, con el objetivo de mejorar el bienestar general y optimizar el funcionamiento del organismo.',
        explicacion: '¿Cómo funciona? A través de una vía intravenosa se administran combinaciones personalizadas que pueden incluir: Vitamina C, Complejo B, Magnesio, Zinc, Aminoácidos, Antioxidantes ¿Para qué está indicada? Fatiga o agotamiento físico, Estrés, Bajos niveles de energía, Déficit vitamínico, Refuerzo del sistema inmunológico, Recuperación post enfermedad o entrenamiento intenso. Permite una absorción directa y rápida, ya que los nutrientes ingresan al torrente sanguíneo sin pasar por el sistema digestivo. La formulación se adapta según las necesidades del paciente.',
        img:''
    },
        {id: 31, 
        rama: "Medicina Funcional",
        servicio: 'Funcional',
        subservicio: 'Sueroterapia',
        descripcion: 'La sueroterapia es un tratamiento que consiste en la administración intravenosa de sueros formulados con vitaminas, minerales, antioxidantes y otros nutrientes, con el objetivo de mejorar el bienestar general y optimizar el funcionamiento del organismo.',
        explicacion: '¿Cómo funciona? A través de una vía intravenosa se administran combinaciones personalizadas que pueden incluir: Vitamina C, Complejo B, Magnesio, Zinc, Aminoácidos, Antioxidantes ¿Para qué está indicada? Fatiga o agotamiento físico, Estrés, Bajos niveles de energía, Déficit vitamínico, Refuerzo del sistema inmunológico, Recuperación post enfermedad o entrenamiento intenso. Permite una absorción directa y rápida, ya que los nutrientes ingresan al torrente sanguíneo sin pasar por el sistema digestivo. La formulación se adapta según las necesidades del paciente.',
        img:''
    },
]